version: 0.2
os: linux

files:
  - source: /
    destination: /var/www/calculator_api
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
artifacts:
  file:
    - '**/*'
  base-directory: base_location